version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.12.0
executors:
  main:
    docker:
      - image: rust:1.56.1-bullseye
  postgres-alongside:
    docker:
      - image: rust:1.56.1-bullseye
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust

jobs:
  build-backend-docker-images:
    resource_class: xlarge
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build base Docker image
          command: |
            docker build -t botloader-base .
      - run:
          name: Build bot
          command: |
            docker build -t jonas747/botloader-bot -f cmd/bot/Dockerfile .
      - run:
          name: Build webapi
          command: |
            docker build -t jonas747/botloader-webapi -f cmd/webapi/Dockerfile .
      - run:
          name: Archive images
          command: |
            docker save -o image-bot.tar jonas747/botloader-bot
            docker save -o image-webapi.tar jonas747/botloader-webapi
      - persist_to_workspace:
          root: .
          paths:
            - ./image-webapi.tar
            - ./image-bot.tar
  publish-backend-images:
    resource_class: medium
    docker:
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived images
          command: |
            docker load -i /tmp/workspace/image-webapi.tar
            docker load -i /tmp/workspace/image-bot.tar
      - run:
          name: Docker login
          command: |
            echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker push "jonas747/botloader-webapi:latest"
            docker push "jonas747/botloader-bot:latest"
            docker tag jonas747/botloader-webapi:latest "jonas747/botloader-webapi:$CIRCLE_BUILD_NUM"
            docker tag jonas747/botloader-bot:latest "jonas747/botloader-bot:$CIRCLE_BUILD_NUM"
            docker push "jonas747/botloader-webapi:$CIRCLE_BUILD_NUM"
            docker push "jonas747/botloader-bot:$CIRCLE_BUILD_NUM"
  build-frontend-image:
    resource_class: medium
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            docker build --build-arg BOTLOADER_API_BASE="https://botloader.io" --build-arg BOTLOADER_CLIENT_ID="907015513073397870" -t jonas747/botloader-frontend . -f frontend/Dockerfile
      - run:
          name: Archive image
          command: |
            docker save -o image-frontend.tar jonas747/botloader-frontend
      - persist_to_workspace:
          root: .
          paths:
            - ./image-frontend.tar
  publish-frontend-images:
    resource_class: medium
    docker:
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived images
          command: |
            docker load -i /tmp/workspace/image-frontend.tar
      - run:
          name: Docker login
          command: |
            echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker push "jonas747/botloader-frontend:latest"
            docker tag jonas747/botloader-frontend:latest "jonas747/botloader-frontend:$CIRCLE_BUILD_NUM"
            docker push "jonas747/botloader-frontend:$CIRCLE_BUILD_NUM"
workflows:
  build-n-publish-frontend:
    jobs:
      - build-frontend-image
      - publish-frontend-images:
          filters:
            branches:
              only: master
          requires:
            - build-frontend-image
  build-n-publish-backend:
    jobs:
      - build-backend-docker-images
      - publish-backend-images:
          filters:
            branches:
              only: master
          requires:
            - build-backend-docker-images
