[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twilight-http = {version = "0.7", features = ["tracing"]}
twilight-model = "0.7"
 
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
tracing-log = "0.1"

tokio = { version = "1.5.0", features = ["full"] }
futures-core = "0.3"
dotenv = "0.15"
structopt = "0.3"
oauth2 = "4.1"
