import type { VerificationLevel } from "./VerificationLevel";
import type { NSFWLevel } from "./NSFWLevel";
import type { PremiumTier } from "./PremiumTier";
import type { ExplicitContentFilter } from "./ExplicitContentFilter";
import type { DefaultMessageNotificationLevel } from "./DefaultMessageNotificationLevel";
import type { MfaLevel } from "./MfaLevel";

export interface Guild {
  afkChannelId: string | null;
  afkTimeout: bigint;
  applicationId: string | null;
  banner: string | null;
  defaultMessageNotifications: DefaultMessageNotificationLevel;
  description: string | null;
  discoverySplash: string | null;
  explicitContentFilter: ExplicitContentFilter;
  features: Array<string>;
  icon: string | null;
  id: string;
  joinedAt: bigint | null;
  large: boolean;
  maxMembers: bigint | null;
  maxPresences: bigint | null;
  memberCount: bigint | null;
  mfaLevel: MfaLevel;
  name: string;
  nsfwLevel: NSFWLevel;
  ownerId: string;
  preferredLocale: string;
  premiumSubscriptionCount: bigint | null;
  premiumTier: PremiumTier;
  rulesChannelId: string | null;
  splash: string | null;
  systemChannelId: string | null;
  unavailable: boolean;
  vanityUrlCode: string | null;
  verificationLevel: VerificationLevel;
  widgetChannelId: string | null;
  widgetEnabled: boolean | null;
}
